### ISSUE TITLE
Apple siliconのMacでサンプルで必要なnumpyのインストールに失敗する

### ISSUE THREAD

**Issue by kadoyau** [VOICEVOX/voicevox_core#129]
## 不具合の内容
コアライブラリをビルドしてサンプルを実行しようとするとサンプルのrequirementsのインストールに失敗しました。

エラーを見てみるとnumpyの導入で失敗しているようで、調べるとApple siliconのmacはnumpy 1.21以降が必要そうです。
https://github.com/numpy/numpy/issues/17807#issuecomment-975689031

直接的な原因はエラーを見る限りここだと思います。
https://github.com/VOICEVOX/pyopenjtalk/blob/07f242eed8e9c2b51e7ee908d46fc789406adefe/pyproject.toml#L6

### 現象・ログ

<details>

```
pip install -r requirements.txt 
Collecting pyopenjtalk
  Cloning https://github.com/VOICEVOX/pyopenjtalk (to revision 69e5f354634f98098113f9cac5a6ea736443f9c9) to /private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-install-4juxky96/pyopenjtalk_6e29b64803fc488e950576702878adf8
  Running command git clone --filter=blob:none --quiet https://github.com/VOICEVOX/pyopenjtalk /private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-install-4juxky96/pyopenjtalk_6e29b64803fc488e950576702878adf8
  Running command git rev-parse -q --verify 'sha^69e5f354634f98098113f9cac5a6ea736443f9c9'
  Running command git fetch -q https://github.com/VOICEVOX/pyopenjtalk 69e5f354634f98098113f9cac5a6ea736443f9c9
  Running command git checkout -q 69e5f354634f98098113f9cac5a6ea736443f9c9
  Resolved https://github.com/VOICEVOX/pyopenjtalk to commit 69e5f354634f98098113f9cac5a6ea736443f9c9
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [220 lines of output]
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting setuptools
        Using cached setuptools-62.2.0-py3-none-any.whl (1.1 MB)
      Collecting cython>=0.21.0
        Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
      Collecting numpy<v1.20.0
        Using cached numpy-1.19.5.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [191 lines of output]
            Running from numpy source directory.
            setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
              run_build = parse_setuppy_commands()
            Processing numpy/random/_bounded_integers.pxd.in
            Processing numpy/random/_philox.pyx
            Processing numpy/random/_bounded_integers.pyx.in
            Processing numpy/random/_sfc64.pyx
            Processing numpy/random/_mt19937.pyx
            Processing numpy/random/bit_generator.pyx
            Processing numpy/random/mtrand.pyx
            Processing numpy/random/_generator.pyx
            Processing numpy/random/_pcg64.pyx
            Processing numpy/random/_common.pyx
            Cythonizing sources
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            blis_info:
              libraries blis not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            openblas_info:
              libraries openblas not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            atlas_3_10_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries tatlas not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            atlas_3_10_blas_info:
              libraries satlas not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            atlas_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries ptf77blas,ptcblas,atlas not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            atlas_blas_info:
              libraries f77blas,cblas,atlas not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            accelerate_info:
              libraries accelerate not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
            Library accelerate was not found. Ignoring
              libraries veclib not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
            Library veclib was not found. Ignoring
              FOUND:
                extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
                extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
                define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

              FOUND:
                extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
                extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
                define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
              libraries mkl_rt not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            openblas_lapack_info:
              libraries openblas not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            openblas_clapack_info:
              libraries openblas,lapack not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            flame_info:
              libraries flame not found in ['/Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            atlas_3_10_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib
              libraries tatlas,tatlas not found in /Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries tatlas,tatlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries tatlas,tatlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
              NOT AVAILABLE

            atlas_3_10_info:
              libraries lapack_atlas not found in /Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib
              libraries satlas,satlas not found in /Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries satlas,satlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries satlas,satlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_3_10_info'>
              NOT AVAILABLE

            atlas_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib
              libraries ptf77blas,ptcblas,atlas not found in /Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries ptf77blas,ptcblas,atlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_threads_info'>
              NOT AVAILABLE

            atlas_info:
              libraries lapack_atlas not found in /Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib
              libraries f77blas,cblas,atlas not found in /Users/kadoyau/ghq/github.com/VOICEVOX/voicevox_core/env/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries f77blas,cblas,atlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries f77blas,cblas,atlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_info'>
              NOT AVAILABLE

              FOUND:
                extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
                extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
                define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

            /private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-build-env-9ahqa98s/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running dist_info
            running build_src
            build_src
            building py_modules sources
            creating build
            creating build/src.macosx-12-arm64-3.9
            creating build/src.macosx-12-arm64-3.9/numpy
            creating build/src.macosx-12-arm64-3.9/numpy/distutils
            building library "npymath" sources
            objc[32257]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1f98cdeb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065ec4f8). One of the two will be used. Which one is undefined.
            objc[32257]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1f98cdf00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065ec548). One of the two will be used. Which one is undefined.
            objc[32257]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1f98cdf50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065ec598). One of the two will be used. Which one is undefined.
            objc[32257]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1f98cdfa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065ec5e8). One of the two will be used. Which one is undefined.
            objc[32257]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1f98cdff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065ec638). One of the two will be used. Which one is undefined.
            objc[32257]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1f98ce040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065ec688). One of the two will be used. Which one is undefined.

            You have not agreed to the Xcode license agreements, please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode license agreements.
            Traceback (most recent call last):
              File "/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/tmp8lprocsf_in_process.py", line 363, in <module>
                main()
              File "/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/tmp8lprocsf_in_process.py", line 345, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/tmp8lprocsf_in_process.py", line 164, in prepare_metadata_for_build_wheel
                return hook(metadata_directory, config_settings)
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-build-env-9ahqa98s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
                self.run_setup()
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-build-env-9ahqa98s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
                super(_BuildMetaLegacyBackend,
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-build-env-9ahqa98s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 508, in <module>
                setup_package()
              File "setup.py", line 500, in setup_package
                setup(**metadata)
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-install-q7xwj9sx/numpy_a2aab6efe31647e4b785c4423f27026e/numpy/distutils/core.py", line 169, in setup
                return old_setup(**new_attr)
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-build-env-9ahqa98s/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
                return distutils.core.setup(**attrs)
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-build-env-9ahqa98s/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
                dist.run_commands()
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-build-env-9ahqa98s/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-build-env-9ahqa98s/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-build-env-9ahqa98s/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 31, in run
                egg_info.run()
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-install-q7xwj9sx/numpy_a2aab6efe31647e4b785c4423f27026e/numpy/distutils/command/egg_info.py", line 24, in run
                self.run_command("build_src")
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-build-env-9ahqa98s/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-build-env-9ahqa98s/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-install-q7xwj9sx/numpy_a2aab6efe31647e4b785c4423f27026e/numpy/distutils/command/build_src.py", line 144, in run
                self.build_sources()
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-install-q7xwj9sx/numpy_a2aab6efe31647e4b785c4423f27026e/numpy/distutils/command/build_src.py", line 155, in build_sources
                self.build_library_sources(*libname_info)
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-install-q7xwj9sx/numpy_a2aab6efe31647e4b785c4423f27026e/numpy/distutils/command/build_src.py", line 288, in build_library_sources
                sources = self.generate_sources(sources, (lib_name, build_info))
              File "/private/var/folders/c3/dzjxr15911lcmx11vt987c7h0000gn/T/pip-install-q7xwj9sx/numpy_a2aab6efe31647e4b785c4423f27026e/numpy/distutils/command/build_src.py", line 378, in generate_sources
                source = func(extension, build_dir)
              File "numpy/core/setup.py", line 663, in get_mathlib_info
                raise RuntimeError("Broken toolchain: cannot link a simple C program")
            RuntimeError: Broken toolchain: cannot link a simple C program
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      × Encountered error while generating package metadata.
      ╰─> See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

</details>

### 再現手順

https://github.com/VOICEVOX/voicevox_core#%E3%82%B3%E3%82%A2%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E3%83%93%E3%83%AB%E3%83%89

### 期待動作

音が生成される？

## OSの種類/ディストリ/バージョン

*   macOS 12.3.1 (チップはM1 Pro)

**Comment by qryxip** [comment]
今のVOICEVOX COREはpyopenjtalkもNumPyも使わなくなっています。なので解決ということでcloseさせて頂きます。

もしAArch64のmacOSで別の問題があったときは、またissueを立てて頂けると助かります。
