### ISSUE TITLE
python example が正常に動作しない

### ISSUE THREAD

**Issue by nebocco** [VOICEVOX/voicevox_core#145]
## 不具合の内容

README.md に記載されている手順で環境構築・サンプル実行を一通り行うとエラーが発生します。

### 現象・ログ

```
PS C:\home\Rust\voicevox_core> python configure.py
Downloading onnxruntime from https://github.com/microsoft/onnxruntime/releases/download/v1.10.0/onnxruntime-win-x64-1.10.0.zip...                                                                                                               Downloading voicevox from https://github.com/VOICEVOX/voicevox_core/releases/download/0.10.0/core.zip...                Please enter number to select which library to use.
0: C:\home\Rust\voicevox_core\release\core_cpu_arm.dll
1: C:\home\Rust\voicevox_core\release\core_cpu_arm64.dll
2: C:\home\Rust\voicevox_core\release\core_cpu_x64.dll
3: C:\home\Rust\voicevox_core\release\core_cpu_x86.dll
4: C:\home\Rust\voicevox_core\release\core_gpu_x64_nvidia.dll
Your choice: 2
Successfully configured!

PS C:\home\Rust\voicevox_core> pip install -r requirements.txt
Requirement already satisfied: numpy in c:\users\personal\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbzPS

C:\home\Rust\voicevox_core> pip install .
Processing c:\home\rust\voicevox_core
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for core, since package 'wheel' is not installed.
Installing collected packages: core
  Attempting uninstall: core
    Found existing installation: core 0.0.1
    Uninstalling core-0.0.1:
      Successfully uninstalled core-0.0.1
  Running setup.py install for core ... done
Successfully installed core-0.0.1

PS C:\home\Rust\voicevox_core> cd .\example\python\

PS C:\home\Rust\voicevox_core\example\python> pip install -r requirements.txt
Collecting pyopenjtalk
  Using cached pyopenjtalk-0.1.4+69e5f35-cp39-cp39-win_amd64.whl
Requirement already satisfied: numpy in c:\users\personal\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 1)) (1.20.2)
Requirement already satisfied: cython in c:\users\personal\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 2)) (0.29.28)
Requirement already satisfied: soundfile in c:\users\personal\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 3)) (0.10.3.post1)
Requirement already satisfied: cffi>=1.0 in c:\users\personal\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from soundfile->-r requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: six in c:\users\personal\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyopenjtalk->-r requirements.txt (line 4)) (1.16.0)
Requirement already satisfied: pycparser in c:\users\personal\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from cffi>=1.0->soundfile->-r requirements.txt (line 3)) (2.21)

PS C:\home\Rust\voicevox_core\example\python> python run.py --speaker_id 1 --text "テスト"
Traceback (most recent call last):
  File "C:\home\Rust\voicevox_core\example\python\run.py", line 50, in <module>
    run(**vars(parser.parse_args()))
  File "C:\home\Rust\voicevox_core\example\python\run.py", line 19, in run
    core.initialize(use_gpu, cpu_num_threads)
  File "C:\Users\Personal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\core\_core.py", line 56, in initialize
    success = lib.initialize(use_gpu, cpu_num_threads, load_all_models)
OSError: exception: access violation reading 0x0000000000000000
```

### 再現手順

リポジトリをクローンし、README.md に記載された手順をなぞる

### 期待動作

`example/run.py` が正常に実行される

## OSの種類/ディストリ/バージョン

Win 10 Pro 64bit 21H2
python 3.9.13
d62a44b, main branch

## その他

ref #137 
`configure.py` でインストールされる voicevox_core のバージョンが 1.10.0 であるため、 API の形式変更による問題が生じているのではないか、という意見をいただきました。（@Yosshi999 さんありがとうございました）

ただし、 `configure.py` を実行せず onnxruntime, `release/` を自分で用意した場合でもエラーが発生します。（読んでいるメモリ位置は異なる）
また `configure.py` を通して環境構築した際には現れなかった、バージョンが対象外である旨の警告も表示されました。
ort は v1.9.0、release は v0.12.0 を使用して確認しました。

```
PS C:\home\Rust\voicevox_core\example\python> python run.py --speaker_id 1 --text "これは本当に実行できているんでしょうか？"
The given version [10] is not supported, only version 1 to 9 is supported in this build.
Traceback (most recent call last):
  File "C:\home\Rust\voicevox_core\example\python\run.py", line 50, in <module>
    run(**vars(parser.parse_args()))
  File "C:\home\Rust\voicevox_core\example\python\run.py", line 19, in run
    core.initialize(use_gpu, cpu_num_threads)
  File "C:\Users\Personal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\core\_core.py", line 56, in initialize
    success = lib.initialize(use_gpu, cpu_num_threads, load_all_models)
OSError: exception: access violation reading 0x0000000000000050
```

**Comment by PickledChair** [comment]
丁寧な Issue ありがとうございます！

先ほど #138 (バージョン 0.12 に対応した python example) をマージしたので、新しい README の手順に従うことで python example を実行できると思います（ @Yosshi999 さんレビューが遅れすみません！）。ただし、configure.py はまだ最新版には対応していません。

**Comment by nebocco** [comment]
迅速なご対応ありがとうございます。実行したところ正常に終了し音声ファイルが生成されました！
いずれ `configure.py` の修正も行う必要があるとは思いますが、こちらはすでに issue が立っている（#137）ため、この issue は閉じさせていただきます。ありがとうございました！
