### ISSUE TITLE
Arch LinuxでGPUモードがSEGVする

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#227]
## 不具合の内容

Arch LinuxでGPUモードを使おうとすると、SEGVが起きます。旧C++実装だと普通に動作します。

### 現象・ログ

```console
❯ sha1sum ./libcore.so ./libonnxruntime.so.1.11.1
3d9669ed2994d03c03ea490e65fdacdf239f9b2c  ./libcore.so
bd1621ce029720b048811c5b9e8041143fce4421  ./libonnxruntime.so.1.11.1
❯ ./voicevox
[02:19:14.176] [info]  Starting 1 engine/s...
[02:19:14.179] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Start launching
[02:19:14.179] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Starting process
[02:19:14.180] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d mode: GPU
[02:19:14.180] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d path: /home/ryo/Downloads/VOICEVOX/run
[02:19:14.180] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d args: ["--use_gpu"]
[02:19:14.988] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )

[02:19:14.995] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: INFO:     Started server process [232236]

[02:19:14.996] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: INFO:     Waiting for application startup.
INFO:     Application startup complete.

[02:19:14.997] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)

[02:19:15.452] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39440 - "GET /version HTTP/1.1" 200 OK

[02:19:15.464] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39440 - "GET /speakers HTTP/1.1" 200 OK

[02:19:15.498] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39456 - "GET /speaker_info?speaker_uuid=35b2c544-660e-401e-b503-0e14c635303a HTTP/1.1" 200 OK

[02:19:15.504] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39474 - "GET /speaker_info?speaker_uuid=b1a81618-b27b-40d2-b0ea-27a9ad408c4b HTTP/1.1" 200 OK

[02:19:15.512] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39472 - "GET /speaker_info?speaker_uuid=3474ee95-c274-47f9-aa1a-8322163d96f1 HTTP/1.1" 200 OK

[02:19:15.516] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39478 - "GET /speaker_info?speaker_uuid=c30dc15a-0992-4f8d-8bb8-ad3b314e6a6f HTTP/1.1" 200 OK

[02:19:15.542] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39440 - "GET /speaker_info?speaker_uuid=7ffcb7ce-00ec-4bdc-82cd-45a8889e43ff HTTP/1.1" 200 OK

[02:19:15.551] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39456 - "GET /speaker_info?speaker_uuid=e5020595-5c5d-4e87-b849-270a518d0dcf HTTP/1.1" 200 OK

[02:19:15.578] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39442 - "GET /speaker_info?speaker_uuid=388f246b-8c41-4ac1-8e2d-5d79f3ff56d9 HTTP/1.1" 200 OK

[02:19:15.587] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39474 - "GET /speaker_info?speaker_uuid=4f51116a-d9ee-4516-925d-21f183e2afad HTTP/1.1" 200 OK

[02:19:15.596] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39472 - "GET /speaker_info?speaker_uuid=8eaad775-3119-417e-8cf4-2a10bfd592c8 HTTP/1.1" 200 OK

[02:19:15.605] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39456 - "GET /speaker_info?speaker_uuid=9f3ee141-26ad-437e-97bd-d22298d02ad2 HTTP/1.1" 200 OK

[02:19:15.611] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39440 - "GET /speaker_info?speaker_uuid=1a17ca16-7ee5-4ea5-b191-2f02ace24d21 HTTP/1.1" 200 OK

[02:19:15.633] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39478 - "GET /speaker_info?speaker_uuid=481fb609-6446-4870-9f46-90c4dd623403 HTTP/1.1" 200 OK

[02:19:15.973] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:39478 - "POST /audio_query?text=&speaker=2 HTTP/1.1" 200 OK

[02:19:24.278] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:36752 - "OPTIONS /synthesis?speaker=2&enable_interrogative_upspeak=false HTTP/1.1" 200 OK

[02:19:29.862] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Process terminated due to receipt of signal SIGSEGV
[02:19:29.862] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Process exited with code null
[02:19:32.344] [error] Error: Failed to fetch
[02:19:32.346] [error] Error: Failed to fetch Failed to fetch AccentPhrases for the text "めたんめたんめたん".
[02:19:32.347] [error] TypeError: Failed to fetch
    at Te.next (app://./js/webpack:/src/openapi/runtime.ts:89:62)
    at Generator.next (<anonymous>)
    at app://./js/webpack:/node_modules/tslib/tslib.es6.js:74:71
    at new Promise (<anonymous>)
    at o (app://./js/webpack:/node_modules/tslib/tslib.es6.js:70:12)
    at Te.fetchApi (app://./js/webpack:/src/openapi/runtime.ts:79:65)
    at Te.next (app://./js/webpack:/src/openapi/runtime.ts:49:37)
    at Generator.next (<anonymous>)
    at app://./js/webpack:/node_modules/tslib/tslib.es6.js:74:71
    at new Promise (<anonymous>)
[02:19:41.697] [info]  All windows closed. Quitting app
[02:19:41.697] [info]  Checking ENGINE status before app quit
[02:19:41.697] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: last exit code: null, signal: SIGSEGV
[02:19:41.697] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Process already closed
[02:19:41.697] [info]  ENGINE 1 / 1 processes killed
```

### 再現手順

製品版のVOICEVOX 0.12.5にRustのlibcore.soとlibonnxruntime.so.1.11.1を入れ、GPUモードで何かしらの入力をする

### 期待動作

SEGVせずに動作する

## OSの種類/ディストリ/バージョン

* Arch Linux (kernel: 5.15.58-2-lts)
* 公式NVIDIAドライバ 515.65.01

## その他

どこでSEGVしているのかわからないため、明日あたり切り分けを行なってみます。

**Comment by Hiroshiba** [comment]
報告ありがとうございます！！切り分け助かります･･･！！！

**Comment by qryxip** [comment]
`use_gpu`をオンにしてsimple_ttsを動かしたところ、`load_model`で(SEGVとかではなく正常に)落ちているっぽいことまで確認しました。

**Comment by qwerty2501** [comment]
Windows GPU版だと正常に動いてるのとWindowsとLinuxで特に実装は変えていないのでなんで落ちてしまうか謎ですね。
C++版なら動作するようなのでダウンロードしてるonnxruntimeが違うものでもなさそうですし

**Comment by qwerty2501** [comment]
そういえば、Rust版のみ軽いモデルは常にCPUを使うようになってましたけど、これが関係してるかも
https://github.com/VOICEVOX/voicevox_core/blob/main/crates/voicevox_core/src/status.rs#L116-L117

**Comment by qryxip** [comment]
(今スマホなのですが)確か`decode_model`の読み込みで失敗していた記憶があります。

**Comment by PickledChair** [comment]
@qwerty2501 

> そういえば、Rust版のみ軽いモデルは常にCPUを使うようになってましたけど、これが関係してるかも
> https://github.com/VOICEVOX/voicevox_core/blob/main/crates/voicevox_core/src/status.rs#L116-L117

C++ 版も軽いモデルは常に CPU を使うようになっていました……（Rust 版を作り始めた時にはなかった条件分岐ですが）。なのでC++ 版と比較してここに違いがあるわけではなさそうです。しかし、だとするとどこに違いがあるんでしょう……🤔

https://github.com/VOICEVOX/voicevox_core/blob/7ff2e7f2ae7e635d2557e2a6114e31b8f8cf3ddd/core/src/core.cpp#L90-L103

**Comment by qwerty2501** [comment]
あれ本当だ

**Comment by qwerty2501** [comment]
あ、 [C++版](https://github.com/VOICEVOX/voicevox_core/blob/0.12.5/core/src/core.cpp#L101) だと  
 `AppendExecutionProvider_CUDA ` のみ実行されているところが、
 [Rust版](https://github.com/VOICEVOX/voicevox_core/blob/main/crates/voicevox_core/src/status.rs#L187-L188) だと 
`with_disable_mem_pattern` , `with_append_execution_provider_cuda` 実行されてるところを見つけました。
`with_disable_mem_pattern` はdirectmlの時のみに実行されているもので、Windows版だと成功していたのはこれが関係してるのかも

**Comment by PickledChair** [comment]
> あ、 [C++版](https://github.com/VOICEVOX/voicevox_core/blob/0.12.5/core/src/core.cpp#L101) だと `AppendExecutionProvider_CUDA ` のみ実行されているところが、 [Rust版](https://github.com/VOICEVOX/voicevox_core/blob/main/crates/voicevox_core/src/status.rs#L187-L188) だと `with_disable_mem_pattern` , `with_append_execution_provider_cuda` 実行されてるところを見つけました。 `with_disable_mem_pattern` はdirectmlの時のみに実行されているもので、Windows版だと成功していたのはこれが関係してるのかも

本当ですね！　これは見落としていました。これを修正して解決するかどうか様子を見たいですね……。

**Comment by qryxip** [comment]
これの続きですが、
- `ORT_USE_CUDA=1`とした上で
- libonnxruntime_providers_{cuda,shared}.soを用意
すればGPUモードの動作ができました。

> ただその先でまだ失敗
と言っていたのはsimple_tts特有の問題だったのでそこを迂回すれば動作できました。

https://github.com/VOICEVOX/voicevox_core/pull/228#issuecomment-1211001103

**Comment by qwerty2501** [comment]
なるほど。
現状providers系のshared libraryは配布対象になっていないので加える必要がありそうですね。

> simple_tts特有の問題だったのでそこを迂回すれば動作できました。

これコード修正必要そうですか？

**Comment by qryxip** [comment]
製品VOICEVOX0.12.5 + CUDAから`with_disable_mem_pattern`を削除する前の声データ入りRust版core(このissueの概要での状況)に、ORT 1.11.1のlibonnxruntime_providers_{cuda,shared}.soを入れればエラーもSEGVもせずに普通に動きました。
core自体には多分コードの修正は要らないと思います。

**Comment by qryxip** [comment]
フルセットのVOICEVOXでSEGVしたのはおそらく古いlibonnxruntime_providers_{cuda,shared}.soを読んでいたからですね...

**Comment by qryxip** [comment]
CUDA関係では要らないというだけでsimple_ttsの実行には何かしらの修正は要るかもしれません。

> なるほど。 現状providers系のshared libraryは配布対象になっていないので加える必要がありそうですね。
> 
> > simple_tts特有の問題だったのでそこを迂回すれば動作できました。
> 
> これコード修正必要そうですか？

`initialize`を`use_gpu=true, load_all_models=true`で呼ぶと、`self.initialized = false`のままここに突入するので確定でこける、という感じの問題に見えました。

https://github.com/VOICEVOX/voicevox_core/blob/18dc02d0efd94b5076d494677b714565662b6c98/crates/voicevox_core/src/internal.rs#L210

**Comment by Hiroshiba** [comment]
> core自体には多分コードの修正は要らないと思います。

CUDAでwith_disable_mem_patterを呼ばない修正は、必須じゃないですが呼ばないほうが速くなるはずなので修正しちゃいたいなという感じですかね･･･！

> CUDA関係では要らないというだけでsimple_ttsの実行には何かしらの修正は要るかもしれません。

ちょっと原因が追えてないのですが、もしよければissue作成かいきなりPR作成かお願いできると嬉しいです！！

**Comment by qryxip** [comment]
> CUDAでwith_disable_mem_patterを呼ばない修正は、必須じゃないですが呼ばないほうが速くなるはずなので修正しちゃいたいなという感じですかね･･･！

あ、いえCUDAでは`with_disable_mem_patter`は呼ばない方がよいと私も思います。言葉が不足していたのですが、「[**CUDA関係ではこれ以上**]多分コードの修正は要らない」という意味でした。

> ちょっと原因が追えてないのですが、もしよければissue作成かいきなりPR作成かお願いできると嬉しいです！！

はい、PR作る方向でいってみます。

**Comment by Hiroshiba** [comment]
あ、なるほどです！PRもありがとうございます、お待ちしています！！
