### ISSUE TITLE
「このオペレーティング システムでは %1 は実行されません」エラー

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#645]
## 不具合の内容

Python版を実行した時にこのようなエラーが表示されました。

```
$ PYTHONPATH=. python ../example/python/run.py
Traceback (most recent call last):
  File "C:\Users\hihok\Github\voicevox_core\example\python\run.py", line 9, in <module>
    import voicevox_core
  File "C:\Users\hihok\Github\voicevox_core\.venv\Lib\site-packages\voicevox_core\__init__.py", line 4, in <module>
    from ._models import (  # noqa: F401
  File "C:\Users\hihok\Github\voicevox_core\.venv\Lib\site-packages\voicevox_core\_models.py", line 7, in <module>
    from ._rust import _to_zenkaku, _validate_pronunciation
ImportError: DLL load failed while importing _rust: このオペレーティング システムでは %1 は実行されません。
```

### 再現手順

Python版の`voicevox_core-0.14.5+directml-cp38-abi3-win_amd64.whl`をインストール。
ダウンローダーを実行。
エラーが出る。

### 期待動作

エラーが出ない。

## その他

（解決はしているのですが、他に遭遇された方がいらっしゃった時のためにメモ書きしておきます。）

**Comment by Hiroshiba** [comment]
基本的にonnxruntime.dllが原因なことが多いと思います。
この場合はDirectML版のpython wheelを使っているけれども、ダウンローダーをデフォルト動作させていた（DirectML版じゃないonnxruntime.dllが降ってきた）状態で実行したので、dllが開けなくてエラーが出たんだと思います。

せめて分かりやすいエラーになると嬉しいかもです。
